### ISSUE TITLE
personal-message

### ISSUE THREAD

**Issue by lisjak** [zoot-hq/zoot#7]
[ ] same styling as chat room
[ ] swipe left to return to previous screen

**Comment by malkamoskowicz** [comment]
@lisjak what do you think of the following improvements:

- icon should indicate how many unread messages there are (and update in real time)
- in the pm list, we should render chatrooms by date (last message sent in room) instead of alphabetically
- chatrooms with unread messages should have some type of indication that there is an unread message there
